"""TV taste quiz — static data only.

19-question quiz that scores the user on 8 TV-specific taste axes.
TV axes differ from movies — serialization tolerance and moral
ambiguity comfort are distinct dimensions that matter much more in
long-form television than in film. See the spec for the axis list.

Shows are presented in a deliberate accessible → challenging order.
Do NOT randomize. Shows with a null response are excluded from
scoring entirely.

Scoring logic lives in taste_quiz_scoring.py — this module is data.
"""

from app.services.taste_quiz_scoring import score_responses as _score

# 8 TV-specific axes. serialization and moral_ambiguity replace the
# movie-quiz's pace and film_history — long-form TV's distinguishing
# dimensions are "will you commit to a slow build" and "can you
# invest in genuinely bad people without needing someone to root for".
AXES: list[dict] = [
    {"key": "serialization",   "label": "Serialization Tolerance", "description": "Commits to long-arc payoff over episodic closure"},
    {"key": "darkness",        "label": "Darkness Tolerance",      "description": "Engages bleak or punishing material"},
    {"key": "moral_ambiguity", "label": "Moral Ambiguity Comfort", "description": "Can invest in genuinely bad people"},
    {"key": "emotional",       "label": "Emotional Register",      "description": "Immersive, character-driven engagement"},
    {"key": "irony",           "label": "Irony Index",             "description": "Detached, deadpan, self-aware"},
    {"key": "comedy",          "label": "Comedy Register",         "description": "Absurdist, transgressive, dark"},
    {"key": "genre",           "label": "Genre Openness",          "description": "Uses genre as a tool, not a filter"},
    {"key": "ambiguity",       "label": "Ambiguity Comfort",       "description": "Surreal, unresolved, unexplained"},
]

AXIS_KEYS: list[str] = [a["key"] for a in AXES]

# Response options — identical to the movie quiz.
RESPONSE_OPTIONS: list[dict] = [
    {"value": 2,    "emoji": "❤️",   "label": "Loved it",        "description": "A real favorite"},
    {"value": 1,    "emoji": "👍",   "label": "Liked it",        "description": "Enjoyed it"},
    {"value": 0,    "emoji": "😐",   "label": "It's fine",       "description": "Neutral"},
    {"value": -1,   "emoji": "👎",   "label": "Didn't click",    "description": "Not for me"},
    {"value": None, "emoji": "🚫",   "label": "Haven't seen it", "description": "Skip"},
]

RATING_MAP: dict[int, int] = {2: 5, 1: 4, 0: 3, -1: 1}

# 24 shows in presentation order. `years` is a string like "2011-2019"
# or "2022-" for still-airing — TMDB's first_air_date only gives us
# the start year, so we pass a `tmdb_year` hint for the TMDB lookup
# and a `years` display string for the UI. `weights` are the axis
# deltas applied when the user rates this show. `generation` and
# `scenes` are Phase D2 tags used by the taste-quiz endpoint to
# filter the pool against the user's saved onboarding picks.
SHOWS: list[dict] = [
    {"order": 1,  "title": "Friends",              "tmdb_year": 1994, "years": "1994–2004",
     "weights": {"emotional": 2, "irony": -2, "ambiguity": -1},
     "generation": ["classic", "millennial", "universal"],
     "scenes": ["comedy", "romance"]},
    {"order": 2,  "title": "The Office",           "tmdb_year": 2005, "years": "2005–2013",
     "weights": {"comedy": 1, "emotional": 1, "irony": 1},
     "generation": ["millennial", "universal"],
     "scenes": ["comedy"]},
    {"order": 3,  "title": "Schitt's Creek",       "tmdb_year": 2015, "years": "2015–2020",
     "weights": {"emotional": 2, "darkness": -2, "irony": -1},
     "generation": ["gen_z", "millennial", "universal"],
     "scenes": ["comedy"]},
    {"order": 4,  "title": "Abbott Elementary",    "tmdb_year": 2021, "years": "2021–",
     "weights": {"emotional": 1, "comedy": 1, "irony": -1, "darkness": -1},
     "generation": ["gen_z"],
     "scenes": ["comedy"]},
    {"order": 5,  "title": "Game of Thrones",      "tmdb_year": 2011, "years": "2011–2019",
     "weights": {"genre": 1, "darkness": 1, "serialization": 1},
     "generation": ["millennial", "gen_z", "universal"],
     "scenes": ["scifi_fantasy", "prestige_drama"]},
    {"order": 6,  "title": "Breaking Bad",         "tmdb_year": 2008, "years": "2008–2013",
     "weights": {"darkness": 2, "moral_ambiguity": 2, "serialization": 1},
     "generation": ["millennial", "universal"],
     "scenes": ["action_thriller", "prestige_drama"]},
    {"order": 7,  "title": "Black Mirror",         "tmdb_year": 2011, "years": "2011–",
     "weights": {"darkness": 2, "genre": 1, "ambiguity": 1},
     "generation": ["millennial", "gen_z"],
     "scenes": ["scifi_fantasy", "prestige_drama"]},
    {"order": 8,  "title": "Seinfeld",             "tmdb_year": 1989, "years": "1989–1998",
     "weights": {"irony": 2, "emotional": -2, "comedy": 1, "moral_ambiguity": 1},
     "generation": ["classic"],
     "scenes": ["comedy"]},
    {"order": 9,  "title": "Succession",           "tmdb_year": 2018, "years": "2018–2023",
     "weights": {"irony": 2, "moral_ambiguity": 2, "darkness": 1, "emotional": -1},
     "generation": ["gen_z", "millennial"],
     "scenes": ["prestige_drama", "comedy"]},
    {"order": 10, "title": "Arrested Development", "tmdb_year": 2003, "years": "2003–2019",
     "weights": {"comedy": 2, "irony": 1, "serialization": 1, "emotional": -1},
     "generation": ["millennial"],
     "scenes": ["comedy"]},
    {"order": 11, "title": "Family Guy",           "tmdb_year": 1999, "years": "1999–",
     "weights": {"comedy": 2, "irony": 1, "genre": 1, "emotional": -2},
     "generation": ["millennial", "gen_z", "universal"],
     "scenes": ["comedy"]},
    {"order": 12, "title": "Fleabag",              "tmdb_year": 2016, "years": "2016–2019",
     "weights": {"emotional": 2, "comedy": 1, "irony": 1, "ambiguity": 1},
     "generation": ["gen_z", "millennial"],
     "scenes": ["comedy", "prestige_drama", "indie_arthouse"]},
    {"order": 13, "title": "Mad Men",              "tmdb_year": 2007, "years": "2007–2015",
     "weights": {"serialization": 2, "moral_ambiguity": 1, "ambiguity": 1, "emotional": 1},
     "generation": ["millennial"],
     "scenes": ["prestige_drama"]},
    {"order": 14, "title": "The Sopranos",         "tmdb_year": 1999, "years": "1999–2007",
     "weights": {"moral_ambiguity": 2, "serialization": 2, "darkness": 1},
     "generation": ["millennial", "universal"],
     "scenes": ["action_thriller", "prestige_drama"]},
    {"order": 15, "title": "The Wire",             "tmdb_year": 2002, "years": "2002–2008",
     "weights": {"serialization": 2, "moral_ambiguity": 1, "darkness": 1, "ambiguity": 1},
     "generation": ["millennial"],
     "scenes": ["action_thriller", "prestige_drama", "true_crime"]},
    {"order": 16, "title": "The Bear",             "tmdb_year": 2022, "years": "2022–",
     "weights": {"darkness": 1, "emotional": 1, "ambiguity": 1},
     "generation": ["gen_z"],
     "scenes": ["prestige_drama", "comedy"]},
    {"order": 17, "title": "True Detective",       "tmdb_year": 2014, "years": "2014",
     "weights": {"darkness": 2, "ambiguity": 2, "moral_ambiguity": 1, "serialization": 1},
     "generation": ["millennial"],
     "scenes": ["true_crime", "action_thriller", "prestige_drama", "horror"]},
    {"order": 18, "title": "Severance",            "tmdb_year": 2022, "years": "2022–",
     "weights": {"ambiguity": 2, "genre": 1, "serialization": 1, "darkness": 1},
     "generation": ["gen_z"],
     "scenes": ["scifi_fantasy", "prestige_drama"]},
    {"order": 19, "title": "The Leftovers",        "tmdb_year": 2014, "years": "2014–2017",
     "weights": {"ambiguity": 2, "emotional": 2, "darkness": 2, "genre": 1},
     "generation": ["millennial"],
     "scenes": ["scifi_fantasy", "prestige_drama", "indie_arthouse"]},
    # Additional items to broaden surface area — warm earnest
    # comfort, absurdist animation, international genre thriller,
    # workplace sitcom, and prestige royal drama.
    {"order": 20, "title": "Ted Lasso",             "tmdb_year": 2020, "years": "2020–2023",
     "weights": {"emotional": 2, "irony": -2, "darkness": -2},
     "generation": ["gen_z"],
     "scenes": ["comedy", "sports"]},
    {"order": 21, "title": "Brooklyn Nine-Nine",    "tmdb_year": 2013, "years": "2013–2021",
     "weights": {"comedy": 1, "emotional": 1, "irony": -1, "darkness": -1},
     "generation": ["millennial", "gen_z"],
     "scenes": ["comedy"]},
    {"order": 22, "title": "Rick and Morty",        "tmdb_year": 2013, "years": "2013–",
     "weights": {"comedy": 2, "irony": 2, "ambiguity": 1, "darkness": 1, "emotional": -1},
     "generation": ["millennial", "gen_z"],
     "scenes": ["comedy", "scifi_fantasy"]},
    {"order": 23, "title": "Squid Game",            "tmdb_year": 2021, "years": "2021–",
     "weights": {"genre": 1, "darkness": 2, "serialization": 1, "moral_ambiguity": 1},
     "generation": ["gen_z", "universal"],
     "scenes": ["k_content", "action_thriller", "prestige_drama"]},
    {"order": 24, "title": "The Crown",             "tmdb_year": 2016, "years": "2016–2023",
     "weights": {"serialization": 2, "emotional": 1, "moral_ambiguity": 1},
     "generation": ["gen_z", "millennial"],
     "scenes": ["prestige_drama", "romance"]},
    # Anime (Phase D3a) — the shonen/seinen anchors plus the
    # acknowledged adult-crossover canon. The son's primary scene.
    {"order": 25, "title": "Demon Slayer",              "tmdb_year": 2019, "years": "2019–",
     "weights": {"genre": 2, "darkness": 1, "emotional": 1, "serialization": 1},
     "generation": ["gen_z"],
     "scenes": ["anime", "action_thriller"]},
    {"order": 26, "title": "Attack on Titan",           "tmdb_year": 2013, "years": "2013–2023",
     "weights": {"genre": 2, "darkness": 2, "moral_ambiguity": 2, "serialization": 2},
     "generation": ["millennial", "gen_z"],
     "scenes": ["anime", "action_thriller", "scifi_fantasy"]},
    {"order": 27, "title": "Jujutsu Kaisen",            "tmdb_year": 2020, "years": "2020–",
     "weights": {"genre": 2, "darkness": 1, "serialization": 1},
     "generation": ["gen_z"],
     "scenes": ["anime", "action_thriller"]},
    {"order": 28, "title": "My Hero Academia",          "tmdb_year": 2016, "years": "2016–",
     "weights": {"genre": 1, "emotional": 1, "serialization": 1, "darkness": -1},
     "generation": ["gen_z"],
     "scenes": ["anime", "action_thriller"]},
    {"order": 29, "title": "Naruto",                    "tmdb_year": 2002, "years": "2002–2017",
     "weights": {"genre": 1, "emotional": 1, "serialization": 2, "darkness": -1},
     "generation": ["millennial", "gen_z"],
     "scenes": ["anime", "action_thriller"]},
    {"order": 30, "title": "Death Note",                "tmdb_year": 2006, "years": "2006–2007",
     "weights": {"genre": 2, "moral_ambiguity": 2, "darkness": 1, "serialization": 1},
     "generation": ["millennial", "gen_z"],
     "scenes": ["anime", "action_thriller", "prestige_drama"]},
    {"order": 31, "title": "Cowboy Bebop",              "tmdb_year": 1998, "years": "1998–1999",
     "weights": {"genre": 2, "ambiguity": 1, "irony": 1, "serialization": -1},
     "generation": ["classic", "millennial"],
     "scenes": ["anime", "scifi_fantasy", "indie_arthouse"]},
    {"order": 32, "title": "Fullmetal Alchemist: Brotherhood", "tmdb_year": 2009, "years": "2009–2010",
     "weights": {"genre": 2, "emotional": 1, "moral_ambiguity": 1, "serialization": 2},
     "generation": ["millennial", "gen_z"],
     "scenes": ["anime", "action_thriller", "prestige_drama"]},
    {"order": 33, "title": "Spy x Family",              "tmdb_year": 2022, "years": "2022–",
     "weights": {"comedy": 1, "emotional": 1, "genre": 1},
     "generation": ["gen_z"],
     "scenes": ["anime", "comedy", "action_thriller"]},
    # Gaming culture (Phase D3a) — the bridge between gaming fandoms
    # and the TV/streaming content those fandoms actually watch.
    {"order": 34, "title": "Arcane",                    "tmdb_year": 2021, "years": "2021–",
     "weights": {"genre": 2, "darkness": 1, "emotional": 1, "serialization": 1},
     "generation": ["gen_z"],
     "scenes": ["gaming_culture", "action_thriller", "scifi_fantasy"]},
    {"order": 35, "title": "The Last of Us",            "tmdb_year": 2023, "years": "2023–",
     "weights": {"darkness": 2, "emotional": 2, "moral_ambiguity": 1, "serialization": 1},
     "generation": ["gen_z"],
     "scenes": ["gaming_culture", "action_thriller", "horror"]},
    {"order": 36, "title": "Castlevania",               "tmdb_year": 2017, "years": "2017–2021",
     "weights": {"genre": 2, "darkness": 2, "serialization": 1},
     "generation": ["gen_z", "millennial"],
     "scenes": ["gaming_culture", "action_thriller", "scifi_fantasy", "horror"]},
    {"order": 37, "title": "Cyberpunk: Edgerunners",    "tmdb_year": 2022, "years": "2022",
     "weights": {"darkness": 2, "genre": 2, "emotional": 1, "moral_ambiguity": 1},
     "generation": ["gen_z"],
     "scenes": ["gaming_culture", "anime", "action_thriller", "scifi_fantasy"]},
    {"order": 38, "title": "Fallout",                   "tmdb_year": 2024, "years": "2024–",
     "weights": {"genre": 2, "darkness": 1, "irony": 1, "serialization": 1},
     "generation": ["gen_z"],
     "scenes": ["gaming_culture", "scifi_fantasy", "action_thriller"]},
    # Action + thrillers (Phase D3b) — husband's primary TV scene.
    # The existing pool had Breaking Bad, The Sopranos, The Wire,
    # and Squid Game but was thin on contemporary thriller series.
    {"order": 39, "title": "Reacher",                    "tmdb_year": 2022, "years": "2022–",
     "weights": {"genre": 1, "darkness": 1},
     "generation": ["gen_z"],
     "scenes": ["action_thriller"]},
    {"order": 40, "title": "Slow Horses",                "tmdb_year": 2022, "years": "2022–",
     "weights": {"genre": 1, "darkness": 1, "moral_ambiguity": 1, "serialization": 1},
     "generation": ["gen_z"],
     "scenes": ["action_thriller", "prestige_drama"]},
    {"order": 41, "title": "Jack Ryan",                  "tmdb_year": 2018, "years": "2018–2023",
     "weights": {"genre": 1, "serialization": 1},
     "generation": ["millennial", "gen_z"],
     "scenes": ["action_thriller"]},
    {"order": 42, "title": "The Boys",                   "tmdb_year": 2019, "years": "2019–",
     "weights": {"genre": 2, "darkness": 2, "moral_ambiguity": 2, "irony": 2},
     "generation": ["gen_z"],
     "scenes": ["action_thriller", "scifi_fantasy", "comedy"]},
    # Comedies (Phase D3b) — workplace + absurdist + ensemble.
    # The existing pool had The Office, Schitt's Creek, Abbott
    # Elementary, Seinfeld, and Brooklyn Nine-Nine but was missing
    # the key absurdist + horror-comedy + Parks-and-Rec-style
    # ensemble anchors.
    {"order": 43, "title": "Parks and Recreation",       "tmdb_year": 2009, "years": "2009–2015",
     "weights": {"comedy": 1, "emotional": 2, "irony": -1, "darkness": -2},
     "generation": ["millennial", "gen_z", "universal"],
     "scenes": ["comedy"]},
    {"order": 44, "title": "What We Do in the Shadows",  "tmdb_year": 2019, "years": "2019–2024",
     "weights": {"comedy": 2, "irony": 2, "genre": 1},
     "generation": ["gen_z"],
     "scenes": ["comedy", "horror"]},
    {"order": 45, "title": "It's Always Sunny in Philadelphia", "tmdb_year": 2005, "years": "2005–",
     "weights": {"comedy": 2, "irony": 2, "moral_ambiguity": 2, "darkness": 1, "emotional": -2},
     "generation": ["millennial", "gen_z", "universal"],
     "scenes": ["comedy"]},
    {"order": 46, "title": "30 Rock",                    "tmdb_year": 2006, "years": "2006–2013",
     "weights": {"comedy": 2, "irony": 2, "emotional": 1},
     "generation": ["millennial"],
     "scenes": ["comedy"]},
    # Horror (Phase D3c) — the TV horror anchors. Previously only
    # True Detective (barely horror) and Castlevania (gaming) and
    # What We Do in the Shadows (comedy-horror) carried the tag.
    {"order": 47, "title": "Stranger Things",            "tmdb_year": 2016, "years": "2016–",
     "weights": {"genre": 2, "emotional": 1, "darkness": 1, "serialization": 1},
     "generation": ["gen_z", "millennial", "universal"],
     "scenes": ["horror", "scifi_fantasy", "kids_family"]},
    {"order": 48, "title": "The Haunting of Hill House", "tmdb_year": 2018, "years": "2018",
     "weights": {"genre": 2, "darkness": 2, "emotional": 2, "serialization": 1},
     "generation": ["gen_z", "millennial"],
     "scenes": ["horror", "prestige_drama"]},
    {"order": 49, "title": "American Horror Story",      "tmdb_year": 2011, "years": "2011–",
     "weights": {"genre": 1, "darkness": 2, "moral_ambiguity": 1},
     "generation": ["millennial", "gen_z"],
     "scenes": ["horror"]},
    {"order": 50, "title": "Yellowjackets",              "tmdb_year": 2021, "years": "2021–",
     "weights": {"genre": 1, "darkness": 2, "moral_ambiguity": 2, "serialization": 1, "ambiguity": 1},
     "generation": ["gen_z"],
     "scenes": ["horror", "prestige_drama"]},
    # Romance (Phase D4a) — previously only Friends + The Crown had
    # romance tags; add the prestige period + contemporary romance TV
    # the audience actually watches.
    {"order": 51, "title": "Bridgerton",                 "tmdb_year": 2020, "years": "2020–",
     "weights": {"emotional": 2, "serialization": 1, "darkness": -1},
     "generation": ["gen_z"],
     "scenes": ["romance", "prestige_drama"]},
    {"order": 52, "title": "Outlander",                  "tmdb_year": 2014, "years": "2014–",
     "weights": {"emotional": 2, "serialization": 2, "genre": 1},
     "generation": ["millennial", "gen_z"],
     "scenes": ["romance", "scifi_fantasy", "prestige_drama"]},
    {"order": 53, "title": "Heartstopper",               "tmdb_year": 2022, "years": "2022–",
     "weights": {"emotional": 2, "darkness": -2, "irony": -1},
     "generation": ["gen_z"],
     "scenes": ["romance", "kids_family"]},
    # K-content (Phase D4a) — previously only Squid Game; add the
    # K-drama + action canon for the K-content fan.
    {"order": 54, "title": "Crash Landing on You",       "tmdb_year": 2019, "years": "2019–2020",
     "weights": {"emotional": 2, "serialization": 2},
     "generation": ["gen_z"],
     "scenes": ["k_content", "romance"]},
    {"order": 55, "title": "Vincenzo",                   "tmdb_year": 2021, "years": "2021",
     "weights": {"genre": 1, "moral_ambiguity": 1, "comedy": 1, "serialization": 1},
     "generation": ["gen_z"],
     "scenes": ["k_content", "action_thriller", "comedy"]},
    {"order": 56, "title": "All of Us Are Dead",         "tmdb_year": 2022, "years": "2022–",
     "weights": {"genre": 2, "darkness": 2, "serialization": 1},
     "generation": ["gen_z"],
     "scenes": ["k_content", "horror", "action_thriller"]},
    # True crime (Phase D4a)
    {"order": 57, "title": "Mindhunter",                 "tmdb_year": 2017, "years": "2017–2019",
     "weights": {"darkness": 2, "pace": 2, "moral_ambiguity": 1, "serialization": 2},
     "generation": ["millennial", "gen_z"],
     "scenes": ["true_crime", "prestige_drama"]},
    {"order": 58, "title": "Tiger King",                 "tmdb_year": 2020, "years": "2020",
     "weights": {"moral_ambiguity": 2, "darkness": 1, "irony": 1},
     "generation": ["gen_z"],
     "scenes": ["true_crime", "docs_nonfiction", "reality_tv"]},
    {"order": 59, "title": "Making a Murderer",          "tmdb_year": 2015, "years": "2015–2018",
     "weights": {"darkness": 2, "moral_ambiguity": 2, "serialization": 2},
     "generation": ["millennial", "gen_z"],
     "scenes": ["true_crime", "docs_nonfiction"]},
    # Reality TV (Phase D4a) — previously zero items with this tag.
    {"order": 60, "title": "The Great British Bake Off", "tmdb_year": 2010, "years": "2010–",
     "weights": {"emotional": 1, "darkness": -2, "irony": -1},
     "generation": ["millennial", "gen_z", "universal"],
     "scenes": ["reality_tv"]},
    {"order": 61, "title": "Love Is Blind",              "tmdb_year": 2020, "years": "2020–",
     "weights": {"emotional": 1, "irony": -1},
     "generation": ["gen_z"],
     "scenes": ["reality_tv", "romance"]},
    {"order": 62, "title": "Queer Eye",                  "tmdb_year": 2018, "years": "2018–",
     "weights": {"emotional": 2, "darkness": -2, "irony": -1},
     "generation": ["gen_z"],
     "scenes": ["reality_tv"]},
    {"order": 63, "title": "RuPaul's Drag Race",         "tmdb_year": 2009, "years": "2009–",
     "weights": {"irony": 1, "comedy": 1, "emotional": 1},
     "generation": ["millennial", "gen_z"],
     "scenes": ["reality_tv", "comedy"]},
    # Sports (Phase D4b) — previously only Ted Lasso. Add prestige
    # sports drama + the doc-series canon the sports fan actually
    # consumes.
    {"order": 64, "title": "Friday Night Lights",        "tmdb_year": 2006, "years": "2006–2011",
     "weights": {"emotional": 2, "serialization": 2, "moral_ambiguity": 1},
     "generation": ["millennial"],
     "scenes": ["sports", "prestige_drama"]},
    {"order": 65, "title": "The Last Dance",             "tmdb_year": 2020, "years": "2020",
     "weights": {"emotional": 1, "pace": 1},
     "generation": ["gen_z", "millennial"],
     "scenes": ["sports", "docs_nonfiction"]},
    {"order": 66, "title": "Drive to Survive",           "tmdb_year": 2019, "years": "2019–",
     "weights": {"emotional": 1, "serialization": 1},
     "generation": ["gen_z"],
     "scenes": ["sports", "docs_nonfiction", "reality_tv"]},
    # Music (Phase D4b)
    {"order": 67, "title": "Daisy Jones & the Six",      "tmdb_year": 2023, "years": "2023",
     "weights": {"emotional": 2, "darkness": 1},
     "generation": ["gen_z"],
     "scenes": ["music", "romance"]},
    # Kids + family (Phase D4b) — adds the all-ages animation that
    # bridges kids_family with anime for the younger viewer.
    {"order": 68, "title": "Avatar: The Last Airbender", "tmdb_year": 2005, "years": "2005–2008",
     "weights": {"emotional": 1, "genre": 1, "serialization": 2, "darkness": -1},
     "generation": ["millennial", "gen_z", "universal"],
     "scenes": ["kids_family", "action_thriller", "scifi_fantasy"]},
    {"order": 69, "title": "Bluey",                      "tmdb_year": 2018, "years": "2018–",
     "weights": {"emotional": 2, "darkness": -2},
     "generation": ["gen_z"],
     "scenes": ["kids_family", "comedy"]},

    # Network procedurals + classic sitcoms + male-skewing reality
    {"order": 70, "title": "NCIS",                       "tmdb_year": 2003, "years": "2003–",
     "weights": {"serialization": -2, "darkness": -1, "moral_ambiguity": -2},
     "generation": ["classic", "millennial", "universal"],
     "scenes": ["action_thriller", "suspense_mystery", "true_crime"]},
    {"order": 71, "title": "Law & Order: SVU",           "tmdb_year": 1999, "years": "1999–",
     "weights": {"serialization": -1, "darkness": 1, "moral_ambiguity": 1},
     "generation": ["classic", "millennial", "universal"],
     "scenes": ["suspense_mystery", "true_crime", "prestige_drama"]},
    {"order": 72, "title": "CSI: Crime Scene Investigation", "tmdb_year": 2000, "years": "2000–2015",
     "weights": {"serialization": -2, "darkness": 1, "ambiguity": -2},
     "generation": ["classic", "millennial"],
     "scenes": ["suspense_mystery", "true_crime"]},
    {"order": 73, "title": "Blue Bloods",                "tmdb_year": 2010, "years": "2010–2024",
     "weights": {"serialization": -1, "darkness": -1, "moral_ambiguity": -1, "emotional": 1},
     "generation": ["classic"],
     "scenes": ["action_thriller", "prestige_drama", "faith_family"]},
    {"order": 74, "title": "Yellowstone",                "tmdb_year": 2018, "years": "2018–",
     "weights": {"serialization": 1, "darkness": 1, "moral_ambiguity": 1, "emotional": 1},
     "generation": ["classic", "millennial"],
     "scenes": ["prestige_drama", "action_thriller"]},
    {"order": 75, "title": "The Big Bang Theory",        "tmdb_year": 2007, "years": "2007–2019",
     "weights": {"comedy": -1, "irony": -1, "emotional": 1, "darkness": -2},
     "generation": ["classic", "millennial", "universal"],
     "scenes": ["comedy"]},
    {"order": 76, "title": "King of Queens",             "tmdb_year": 1998, "years": "1998–2007",
     "weights": {"comedy": -1, "irony": -1, "emotional": 1, "darkness": -2},
     "generation": ["classic", "millennial"],
     "scenes": ["comedy"]},
    {"order": 77, "title": "Everybody Loves Raymond",    "tmdb_year": 1996, "years": "1996–2005",
     "weights": {"comedy": -1, "irony": -1, "emotional": 1},
     "generation": ["classic"],
     "scenes": ["comedy"]},
    {"order": 78, "title": "Home Improvement",           "tmdb_year": 1991, "years": "1991–1999",
     "weights": {"comedy": -1, "irony": -1, "darkness": -2, "emotional": 1},
     "generation": ["classic"],
     "scenes": ["comedy", "kids_family"]},
    {"order": 79, "title": "24",                         "tmdb_year": 2001, "years": "2001–2014",
     "weights": {"serialization": 2, "darkness": 2, "moral_ambiguity": 2},
     "generation": ["classic", "millennial"],
     "scenes": ["action_thriller", "suspense_mystery"]},
    {"order": 80, "title": "Survivor",                   "tmdb_year": 2000, "years": "2000–",
     "weights": {"serialization": 1, "moral_ambiguity": 1, "darkness": -1},
     "generation": ["classic", "millennial", "universal"],
     "scenes": ["reality_tv"]},
    {"order": 81, "title": "The Amazing Race",           "tmdb_year": 2001, "years": "2001–",
     "weights": {"serialization": -1, "darkness": -2, "emotional": 1},
     "generation": ["classic", "millennial"],
     "scenes": ["reality_tv"]},
    {"order": 82, "title": "Gold Rush",                  "tmdb_year": 2010, "years": "2010–",
     "weights": {"serialization": -1, "darkness": -1, "emotional": -1},
     "generation": ["classic"],
     "scenes": ["reality_tv", "docs_nonfiction"]},
    {"order": 83, "title": "Deadliest Catch",            "tmdb_year": 2005, "years": "2005–",
     "weights": {"serialization": -1, "darkness": 1, "emotional": 1},
     "generation": ["classic"],
     "scenes": ["reality_tv", "docs_nonfiction"]},
    {"order": 84, "title": "This Old House",             "tmdb_year": 1979, "years": "1979–",
     "weights": {"serialization": -2, "darkness": -2, "emotional": -1},
     "generation": ["classic"],
     "scenes": ["reality_tv", "self_improvement"]},
    {"order": 85, "title": "Fixer Upper",                "tmdb_year": 2013, "years": "2013–2018",
     "weights": {"serialization": -2, "darkness": -2, "emotional": 1},
     "generation": ["classic", "millennial"],
     "scenes": ["reality_tv", "self_improvement", "feelgood_comfort"]},
    {"order": 86, "title": "Homeland",                   "tmdb_year": 2011, "years": "2011–2020",
     "weights": {"serialization": 2, "darkness": 2, "moral_ambiguity": 2},
     "generation": ["classic", "millennial"],
     "scenes": ["action_thriller", "suspense_mystery", "prestige_drama"]},
    {"order": 87, "title": "Criminal Minds",             "tmdb_year": 2005, "years": "2005–2020",
     "weights": {"serialization": -1, "darkness": 2, "moral_ambiguity": 1},
     "generation": ["classic", "millennial"],
     "scenes": ["suspense_mystery", "true_crime"]},
    {"order": 88, "title": "Chicago Fire",               "tmdb_year": 2012, "years": "2012–",
     "weights": {"serialization": -1, "darkness": -1, "emotional": 2},
     "generation": ["classic", "millennial"],
     "scenes": ["action_thriller", "prestige_drama"]},
    {"order": 89, "title": "The Curse of Oak Island",    "tmdb_year": 2014, "years": "2014–",
     "weights": {"serialization": 1, "darkness": -2, "ambiguity": 1},
     "generation": ["classic"],
     "scenes": ["reality_tv", "docs_nonfiction", "history_war"]},

    # Classic cable procedurals — accessible, character-driven
    {"order": 90, "title": "House",                      "tmdb_year": 2004, "years": "2004–2012",
     "weights": {"moral_ambiguity": 2, "irony": 1, "comedy": 1, "darkness": 1},
     "generation": ["classic", "millennial"],
     "scenes": ["prestige_drama", "comedy", "suspense_mystery"]},
    {"order": 91, "title": "Monk",                       "tmdb_year": 2002, "years": "2002–2009",
     "weights": {"irony": -1, "emotional": 1, "darkness": -2, "comedy": -1},
     "generation": ["classic", "millennial"],
     "scenes": ["comedy", "suspense_mystery", "feelgood_comfort"]},
    {"order": 92, "title": "Psych",                      "tmdb_year": 2006, "years": "2006–2014",
     "weights": {"irony": 1, "comedy": 1, "darkness": -2},
     "generation": ["classic", "millennial"],
     "scenes": ["comedy", "suspense_mystery"]},
    {"order": 93, "title": "Bones",                      "tmdb_year": 2005, "years": "2005–2017",
     "weights": {"serialization": -1, "darkness": 1, "emotional": 1},
     "generation": ["classic", "millennial"],
     "scenes": ["suspense_mystery", "true_crime", "romance"]},
    {"order": 94, "title": "The Blacklist",              "tmdb_year": 2013, "years": "2013–2023",
     "weights": {"serialization": 2, "moral_ambiguity": 2, "darkness": 1},
     "generation": ["classic", "millennial"],
     "scenes": ["action_thriller", "suspense_mystery"]},
    {"order": 95, "title": "Castle",                     "tmdb_year": 2009, "years": "2009–2016",
     "weights": {"irony": 1, "emotional": 1, "darkness": -1},
     "generation": ["classic", "millennial"],
     "scenes": ["suspense_mystery", "comedy", "romance"]},
    {"order": 96, "title": "White Collar",               "tmdb_year": 2009, "years": "2009–2014",
     "weights": {"irony": 1, "moral_ambiguity": 1, "darkness": -1},
     "generation": ["classic", "millennial"],
     "scenes": ["suspense_mystery", "comedy"]},

    # Network dramas + classics
    {"order": 97, "title": "Grey's Anatomy",             "tmdb_year": 2005, "years": "2005–",
     "weights": {"serialization": 2, "emotional": 2, "darkness": 1},
     "generation": ["classic", "millennial", "universal"],
     "scenes": ["prestige_drama", "romance"]},
    {"order": 98, "title": "ER",                         "tmdb_year": 1994, "years": "1994–2009",
     "weights": {"serialization": 1, "emotional": 2, "darkness": 1},
     "generation": ["classic"],
     "scenes": ["prestige_drama", "action_thriller"]},
    {"order": 99, "title": "The X-Files",                "tmdb_year": 1993, "years": "1993–2002",
     "weights": {"serialization": 1, "ambiguity": 2, "genre": 2, "darkness": 1},
     "generation": ["classic", "millennial"],
     "scenes": ["scifi_fantasy", "suspense_mystery", "horror"]},
    {"order": 100, "title": "M*A*S*H",                   "tmdb_year": 1972, "years": "1972–1983",
     "weights": {"emotional": 2, "irony": 1, "comedy": 1, "darkness": 1},
     "generation": ["classic"],
     "scenes": ["comedy", "prestige_drama", "history_war"]},
    {"order": 101, "title": "This Is Us",                "tmdb_year": 2016, "years": "2016–2022",
     "weights": {"emotional": 2, "serialization": 2, "darkness": -1},
     "generation": ["classic", "millennial"],
     "scenes": ["prestige_drama", "feelgood_comfort"]},

    # Competition & reality
    {"order": 102, "title": "The Voice",                 "tmdb_year": 2011, "years": "2011–",
     "weights": {"emotional": 1, "serialization": -1, "darkness": -2},
     "generation": ["classic", "millennial", "universal"],
     "scenes": ["reality_tv", "music"]},
    {"order": 103, "title": "American Idol",             "tmdb_year": 2002, "years": "2002–",
     "weights": {"emotional": 1, "serialization": -1, "darkness": -2},
     "generation": ["classic", "millennial", "universal"],
     "scenes": ["reality_tv", "music"]},
    {"order": 104, "title": "Shark Tank",                "tmdb_year": 2009, "years": "2009–",
     "weights": {"moral_ambiguity": 1, "irony": -1, "darkness": -2},
     "generation": ["classic", "millennial"],
     "scenes": ["reality_tv", "self_improvement"]},
    {"order": 105, "title": "Top Chef",                  "tmdb_year": 2006, "years": "2006–",
     "weights": {"serialization": 1, "darkness": -1},
     "generation": ["classic", "millennial"],
     "scenes": ["reality_tv", "cooking_food"]},
    {"order": 106, "title": "Forged in Fire",            "tmdb_year": 2015, "years": "2015–",
     "weights": {"darkness": -1, "serialization": -2},
     "generation": ["classic"],
     "scenes": ["reality_tv", "history_war"]},
    {"order": 107, "title": "Alone",                     "tmdb_year": 2015, "years": "2015–",
     "weights": {"darkness": 1, "serialization": 1, "emotional": 1},
     "generation": ["classic", "millennial"],
     "scenes": ["reality_tv", "docs_nonfiction"]},

    # Modern mainstream
    {"order": 108, "title": "Downton Abbey",             "tmdb_year": 2010, "years": "2010–2015",
     "weights": {"serialization": 2, "emotional": 2, "darkness": -1, "irony": -1},
     "generation": ["classic", "millennial"],
     "scenes": ["prestige_drama", "history_war", "romance"]},
    {"order": 109, "title": "Virgin River",              "tmdb_year": 2019, "years": "2019–",
     "weights": {"emotional": 2, "serialization": 1, "darkness": -2},
     "generation": ["classic", "millennial"],
     "scenes": ["romance", "feelgood_comfort"]},
]


PROFILES: list[dict] = [
    {
        "id": "long_game_player",
        "name": "The Long Game Player",
        "vector": {"serialization": 1.0, "moral_ambiguity": 1.0, "darkness": 1.0},
        "description": "You treat TV as the medium's truest form. Patience is a prerequisite, not a sacrifice. You commit to slow-build dramas that trust you to follow a long arc, and you're rewarded for staying with them.",
    },
    {
        "id": "dark_comedy_devotee",
        "name": "The Dark Comedy Devotee",
        "vector": {"irony": 1.0, "comedy": 1.0, "moral_ambiguity": 1.0},
        "description": "Warmth makes you suspicious. You want wit, transgression, and no one to root for — and you find that more honest than sentimentality.",
    },
    {
        "id": "emotionally_invested",
        "name": "The Emotionally Invested",
        "vector": {"emotional": 1.0, "irony": -1.0, "darkness": -0.5},
        "description": "Character is everything. You're not looking to be provoked — you're looking to recognize something true. You're drawn to shows that trust small moments and earn their feelings.",
    },
    {
        "id": "comfortable_rewatcher",
        "name": "The Comfortable Rewatcher",
        "vector": {"emotional": 1.0, "serialization": -1.0, "darkness": -1.0},
        "description": "You know what you like and you return to it. TV is pleasure, not a commitment or a challenge. You want warmth, familiarity, and stories that leave you lighter than they found you.",
    },
    {
        "id": "ambiguity_seeker",
        "name": "The Ambiguity Seeker",
        "vector": {"ambiguity": 1.0, "genre": 1.0, "emotional": -0.5},
        "description": "You want TV to destabilize, not reassure. You're drawn to shows that withhold answers, shift reality, or leave you uncertain about what you just watched.",
    },
    {
        "id": "prestige_convert",
        "name": "The Prestige Convert",
        "vector": {"serialization": 1.0, "moral_ambiguity": 1.0, "emotional": 0.3},
        "description": "You think of the best dramas in the same breath as great novels. You want craft, patience, and long-form storytelling that pays off character work episode by episode.",
    },
    # Scene-driven profile signatures (Phase E2). Axis-proxy vectors
    # that light up when the user rates items in the underserved
    # scenes highly — sitcom + cozy comedy, TV horror, and period /
    # contemporary TV romance.
    {
        "id": "cozy_comedy_fan",
        "name": "The Cozy Comedy Fan",
        "vector": {"comedy": 1.0, "emotional": 1.0, "darkness": -1.0, "irony": -0.3},
        "description": "You watch TV to feel good. Parks and Rec, Schitt's Creek, Abbott Elementary, Ted Lasso — warm sitcoms with hearts the size of small countries are exactly your thing, and you're right that the mean stuff is usually just mean.",
    },
    {
        "id": "horror_completist_tv",
        "name": "The Horror Completist",
        "vector": {"genre": 1.0, "darkness": 1.0, "ambiguity": 0.5, "moral_ambiguity": 0.3},
        "description": "TV horror is its own country and you've mapped it — Hill House to Yellowjackets to Stranger Things. You want atmosphere, long-arc dread, and shows that are willing to commit to the bit instead of pulling punches.",
    },
    {
        "id": "period_romantic",
        "name": "The Period Romantic",
        "vector": {"serialization": 1.0, "emotional": 1.0, "darkness": -0.5},
        "description": "Bridgerton, The Crown, Outlander — you want TV that takes romance seriously, rewards long commitments, and gives you beautiful people in beautiful clothes making decisions you'll still be thinking about next week.",
    },
]


# Below the movie quiz threshold because there are 19 shows, not 20,
# and TV taste tends to be more hybrid than film taste so we want to
# surface a profile slightly earlier.
MIN_ANSWERED = 8


def score_responses(responses: list[dict]) -> dict:
    """Score quiz responses against the TV data. Thin wrapper that
    delegates the actual math to taste_quiz_scoring._score."""
    return _score(
        responses=responses,
        items=SHOWS,
        axis_keys=AXIS_KEYS,
        profiles=PROFILES,
        min_answered=MIN_ANSWERED,
    )
